### ISSUE TITLE
Timestamps in dataset

### ISSUE THREAD

**Issue by pushkalkatara** [castacks/tartanair_tools#1]
Hi, KITTI also provides timestamp  between each frame. 

As the images are generated from simulator, which exported ground truth at particular fps. I think it would be a heloful additon the dataset.

**Comment by Amigoshan** [comment]
The short answer is you can go ahead and generate a list of timestamps by assuming the data is collected in some frequency (10-30 HZ would all be reasonable). 
 
The data is collected in AirSim Computer Vision mode, where no robot kinematics or dynamics is involved. As we described in the paper, we first sample the trajectories in the free space, and generate camera poses along the trajectory. So in our data collection pipeline, there's no concept of timestamp.  But when we set up the parameters, we do have in mind that the resulting trajectory should follow some reasonable velocity and acceleration. For example, if we assume the images are in 20 Hz, the max velocity in the easy mode is about 5m/s, 10m/s in the hard mode.
