### ISSUE TITLE
Error : QUATERNION_FORMAT_ILLEGAL: Quaternion should be normalized!

### ISSUE THREAD

**Issue by letsgofeng** [castacks/tartanair_tools#10]
Hi, I participate TartanAir Visual SLAM challenge, the submission results were error (quaternion format illegal). But the quaternion have been normalized, and there are no the error in the evaluation code(tartanair_tools). I would like to know the reason, looking forward to receiving your reply as soon as possible.

**Comment by Amigoshan** [comment]
Sorry for the delayed reply! Could you please send a result file with the above problem to tartanair@hotmail.com? We will look into the problem.

**Comment by letsgofeng** [comment]
Thanks. I have solved it by increasing the precision of quaternion about QUATERNION_FORMAT_ILLEGAL, but there is another problem (Error : It is not currently possible to manually set the aspect on 3D axes). I look forward to your reply.

**Comment by Amigoshan** [comment]
Yes, this error appeared since last Friday. I'm waiting for the reply from AICrowd. It should be fixed soon.
