### ISSUE TITLE
Where can we get the camera  model?

### ISSUE THREAD

**Issue by ganlumomo** [castacks/tartanair_tools#11]
I am generating point cloud data from the depth images, but could not find camera intrinsic parameters.
Could you please give me some advice on this? Thank you so much!

**Comment by ganlumomo** [comment]
Sorry, just found the parameters!  - -!

**Comment by LeonardoRez** [comment]
> Sorry, just found the parameters! - -!

where?

**Comment by LeonardoRez** [comment]
Oh, it was answered here: https://github.com/castacks/tartanair_tools/issues/3
