### ISSUE TITLE
How to get pose of data

### ISSUE THREAD

**Issue by Yvaine** [castacks/tartanair_tools#18]
Hi,
When use 
`python download_training.py  --depth --only-easy --rgb --only-left --azcopy`,
 how to get the pose of images?

**Comment by GopiRajuMatta** [comment]
Hello,

I am also not able to download pose files. Can you please suggest how to proceed with it.

Thank you
Gopi

**Comment by kwea123** [comment]
the pose are inside each of the .zip file
