### ISSUE TITLE
Ground truth labels for semantic segmentation

### ISSUE THREAD

**Issue by Jhonatas-17** [castacks/tartanair_tools#22]
I downloaded the segmentation maps available in the dataset, however, I can't find the labels for each object. Would you have a table with this information? As in the following example:
'0000 -> car'
'0001 -> trees'
'0002' -> sky '
if there is no such thing, would there be any way for me to get to that information myself? Is there any code or tool to help with this task?

**Comment by Amigoshan** [comment]
The segmentation labels come from the AirSim interface: https://github.com/microsoft/AirSim/blob/master/docs/image_apis.md#segmentation
It currently doesn't have a list. The labels from different environments could be inconsistent and might need some effort to align them. If you are interested in contributing and making the labels better, that would be very helpful!

**Comment by Jhonatas-17** [comment]
Thank you very much!
