### ISSUE TITLE
Camera Calibration in the SLAM dataset

### ISSUE THREAD

**Issue by ferreram** [castacks/tartanair_tools#3]
Hi,
Thanks for sharing this dataset! I was wondering where I could find the camera calibration parameters related to the SLAM challenge?
Thanks!

**Comment by ngthanhtin** [comment]
@ferreram Camera parameters are defined here: https://github.com/castacks/tartanair_tools/blob/master/data_type.md

**Comment by ferreram** [comment]
Ok thanks @ngthanhtin !
