### ISSUE TITLE
have the provided stereo images been stereo rectified?

### ISSUE THREAD

**Issue by LongruiDong** [castacks/tartanair_tools#35]
Hi~
Thanks for presenting such an amazing dataset!
do I need to undiostort images?
have the provided stereo images been stereo rectified?

**Comment by Qjizhi** [comment]
> Hi~ Thanks for presenting such an amazing dataset! do I need to undiostort images? have the provided stereo images been stereo rectified?

I think the stereo images are already rectified, and I used them for training
