### ISSUE TITLE
download url seems unavailable

### ISSUE THREAD

**Issue by StereoResearcher** [castacks/tartanair_tools#45]
Dear Professor:
The link "https://github.com/castacks/tartanair_tools/blob/master/download_training_zipfiles.txt" and other similar url seems not available in Tartanair project.
"wget -c https://tartanair.blob.core.windows.net/tartanair-release1/*/*/depth_left.zip" returns an Error

Warning: wildcards not supported in HTTP.
https://tartanair.blob.core.windows.net/tartanair-release1/*/*/depth_left.zip
Resolving tartanair.blob.core.windows.net (tartanair.blob.core.windows.net)... 52.239.169.4
Connecting to tartanair.blob.core.windows.net (tartanair.blob.core.windows.net)|52.239.169.4|:443... connected.
HTTP request sent, awaiting response... 403 The specified account is disabled.
ERROR 403: The specified account is disabled..

**Comment by senecobis** [comment]
Same here, seems that the host account is no longer available

**Comment by WilliamLambertCN** [comment]
Same here again, return 403 error when downloading.
--2023-06-14 09:49:09-- [https://tartanair.blob.core.windows.net/tartanair-release1/amusement/Easy/depth_left.zip](vscode-file://vscode-app/d:/DL_Kits/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) Resolving tartanair.blob.core.windows.net (tartanair.blob.core.windows.net)... 52.239.169.4 Connecting to tartanair.blob.core.windows.net (tartanair.blob.core.windows.net)|52.239.169.4|:443... connected. HTTP request sent, awaiting response... 403 The specified account is disabled. 2023-06-14 09:49:10 ERROR 403: The specified account is disabled..

**Comment by zitongzhan** [comment]
Same here

**Comment by a541203686** [comment]
Same here

**Comment by dingangui** [comment]
same here, and where can we download the datasets now?

**Comment by senecobis** [comment]
After "discussing" with the team, I think they are aware of the issue and it would be fixed in few days.

**Comment by RohitChoudharyManth** [comment]
The dataset was getting downloaded earlier, but now it shows the following error.

"Resolving tartanair.blob.core.windows.net (tartanair.blob.core.windows.net)... failed: Name or service not known.
wget: unable to resolve host address ‘tartanair.blob.core.windows.net’"

**Comment by surajiitd** [comment]
I only need the **test-set (Monocular track)** of TartanAir, does anyone has any alternative.
this link is not accessible from the browser itself: https://tartanair.blob.core.windows.net/tartanair-testing1/tartanair-test-mono-release.tar.gz
So the servers are down. Please share some alternative for the  @**TEST-SET**
@casstacks

**Comment by MehdiShahbazi** [comment]
Could you kindly provide an update regarding the links, please?

**Comment by andrewjong** [comment]
We recently lost access to Microsoft Azure which held our dataset. We are looking at how to host an alternative solution. I've messaged the project lead, Wenshan Wang, just now.

**Comment by girish1511** [comment]
Hi, is there an update regarding this situation? Thanks

**Comment by MehdiShahbazi** [comment]
Could you please let me know if there has been any update on this? I am using this dataset in an ongoing project. Sincere, thanks.

**Comment by Amigoshan** [comment]
Hi, the dataset is back online! 
We are so sorry for the inconvenience!
