### ISSUE TITLE
inaccurate sky depth for amusement

### ISSUE THREAD

**Issue by kwea123** [castacks/tartanair_tools#46]
Just in case someone falls into this trap like me:
<img width="897" alt="截圖 2023-07-15 下午3 53 35" src="https://github.com/castacks/tartanair_tools/assets/11364490/ab0be2c2-5c36-4b78-b69a-6cd4abd1e75e">

The sky depth for `amusement` scene is corrupted, it seems there is a invisible dome capping the max depth. We can use the segmentation to somehow correct the depth, but segmentation (id=182) is inaccurate too, it contains some of the trees (so it means they are the same mesh?). Setting the depth value of this class to be something like 100 should be a somehow reasonable solution.

**Comment by Guptajakala** [comment]
@kwea123 bumping into the same issue. Did you solve the problem?
