### ISSUE TITLE
Can't download training zipfiles

### ISSUE THREAD

**Issue by aneurintoomey** [castacks/tartanair_tools#57]
Hello. As stated n the subject line I'm having issues taking a local copy of the dataset using the provided download_training.py. I've copied the error I'm getting below. Are the access keys expired?

`Traceback (most recent call last):
  File "/home/desktop1/Documents/tartanair_tools/download_training.py", line 195, in <module>
    content_list = get_all_s3_objects(s3, bucket_name)
  File "/home/desktop1/Documents/tartanair_tools/download_training.py", line 92, in get_all_s3_objects
    response = s3.list_objects_v2(**list_kwargs)
  File "/home/desktop1/.local/lib/python3.10/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/desktop1/.local/lib/python3.10/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Unauthorized) when calling the ListObjectsV2 operation: Unauthorized`

**Comment by wynelio** [comment]
I also encountered this problem. I successfully downloaded it three days ago, but today the above problem occurred during the download.

**Comment by zhangcv123** [comment]
+1

**Comment by Amigoshan** [comment]
Sorry for the inconvenience! The download script has been updated! 
We also added another downloading source, which hopefully will reduce the chance of data not being available.

**Comment by Amigoshan** [comment]
Please open another issue if there are any further problems!
