### ISSUE TITLE
camera internal and external parameters?

### ISSUE THREAD

**Issue by letsgofeng** [castacks/tartanair_tools#6]
Hi, I find no camera internal and external parameters provided in the stereo track dataset, and there are no instructions or download links elsewhere,  is this data not provided?

**Comment by Amigoshan** [comment]
Hi, please check out the information here: https://github.com/castacks/tartanair_tools/blob/master/data_type.md

**Comment by letsgofeng** [comment]
> Hi, please check out the information here: https://github.com/castacks/tartanair_tools/blob/master/data_type.md
> A similar issue here: #3

**Comment by chaizheng2157** [comment]
There is only camera intrinsic params in the data_type.md, where are the extrinsic params for the stereo camera?   Do not find the transformation between the left and right cams.

**Comment by Amigoshan** [comment]
The baseline between the left and right cameras are 0.25m. You can find an example here: https://github.com/castacks/tartanair_tools/blob/master/data_type.md#depth-image
