### ISSUE TITLE
Licensing issue regarding the submission terms and conditions

### ISSUE THREAD

**Issue by yan99033** [castacks/tartanair_tools#7]
I might be interpreting the terms incorrectly, so let me know if I am wrong.

What I have read here is that I will lose the intellectual right for the novelty of my proposed method once I have submitted the results, am I right? Even if I would like to publish the results in my future paper, I won't be able to claim the results as mine, because the results belong to "the sole property of Alcrowd".

Please advice.

![image](https://user-images.githubusercontent.com/26388965/84708037-fc983500-af1c-11ea-8145-bc85aac57ec5.png)
![image](https://user-images.githubusercontent.com/26388965/84708073-0c177e00-af1d-11ea-9c72-9bcbe060a446.png)

**Comment by Amigoshan** [comment]
Thanks for the question!
This challenge doesn't require participants to upload code and materials other than a zip file containing the results. I don't think there will be anything preventing you from publishing a paper in the future. 
Let me contact the people from the AICrowd and get back to you with a more formal answer soon.

**Comment by Amigoshan** [comment]
Hi, this is a reply from the AICrowd. 
Based on the terms of the platform, the participants still retain the ownership and IP of anything submitted. They allow AICrowd to use any submitted material only for the usage related to this competition (evaluation for scoring them in this case).
As for us organizers, we don't require any IP transfer either.
